import type { Bill } from "@/lib/types";

export const seedBills: Bill[] = [
  {
    id: "us-hr-3021",
    slug: "federal-hr-3021-ai-settlement-disclosures",
    title: "AI-Assisted Settlement Services Disclosure Act",
    jurisdiction: "federal",
    billNumber: "H.R. 3021",
    status: "in_committee",
    lastUpdated: "2026-04-12T14:30:00Z",
    hearingDate: "2026-04-22T15:00:00Z",
    titleRelevance: "Would require settlement providers to disclose AI-assisted document preparation and audit workflows.",
    summary: "Creates federal disclosure rules for AI use in settlement, escrow, and title-curative workflows.",
    sourceDocuments: [
      {
        id: "src-hr3021-text",
        label: "Congress.gov bill text",
        url: "https://www.congress.gov/",
        publishedAt: "2026-04-10T12:00:00Z",
        sourceType: "bill_text",
      },
    ],
    impactSummary: {
      summary: "Title agencies and underwriters would need new disclosure language in closing packages when AI contributes to document review or exception handling.",
      impactLevel: "high",
      affectedStakeholders: ["Title agents", "Underwriters", "Compliance officers"],
      citations: ["Congress.gov bill text"],
      freshnessLabel: "Updated 2 days ago",
      draft: true,
    },
    guidanceDraft: {
      summary: "Draft updated settlement package disclosures and internal AI usage attestations before committee markup.",
      recommendedActions: [
        "Inventory AI-assisted workflows in title production",
        "Prepare model disclosure language for closing packages",
      ],
      citations: ["Congress.gov bill text"],
      draft: true,
    },
    auditTrail: [
      {
        id: "audit-hr3021-1",
        at: "2026-04-12T14:32:00Z",
        actor: "system:seed",
        action: "bill.seeded",
        detail: "Seeded federal bill with draft impact summary and guidance.",
      },
    ],
  },
  {
    id: "ca-ab-915",
    slug: "ca-ab-915-title-rate-transparency",
    title: "Title Rate Transparency and Consumer Access Act",
    jurisdiction: "CA",
    billNumber: "AB 915",
    status: "on_floor",
    lastUpdated: "2026-04-14T18:00:00Z",
    titleRelevance: "Would force public-facing disclosure of title premium components and local filing references.",
    summary: "Expands consumer-facing disclosure obligations for title insurance rate components and endorsements.",
    sourceDocuments: [
      {
        id: "src-ca-ab915",
        label: "California bill summary",
        url: "https://leginfo.legislature.ca.gov/",
        publishedAt: "2026-04-14T17:00:00Z",
        sourceType: "summary",
      },
    ],
    impactSummary: {
      summary: "California agencies would need refreshed rate disclosure templates and stronger public documentation around endorsement pricing.",
      impactLevel: "high",
      affectedStakeholders: ["California title agents", "Compliance teams", "Consumer ops"],
      citations: ["California bill summary"],
      freshnessLabel: "Updated today",
      draft: true,
    },
    auditTrail: [
      {
        id: "audit-ca-ab915-1",
        at: "2026-04-14T18:02:00Z",
        actor: "system:seed",
        action: "bill.seeded",
        detail: "Seeded CA bill with fresh floor-status metadata.",
      },
    ],
  },
  {
    id: "tx-sb-1440",
    slug: "tx-sb-1440-digital-closing-standards",
    title: "Digital Closing Integrity Act",
    jurisdiction: "TX",
    billNumber: "SB 1440",
    status: "passed",
    lastUpdated: "2026-04-08T13:15:00Z",
    titleRelevance: "Sets operational standards for hybrid digital closings and title file retention in Texas.",
    summary: "Creates state-level controls for digital closing evidence, title file retention, and exception auditability.",
    sourceDocuments: [
      {
        id: "src-tx-sb1440",
        label: "Texas Legislature bill text",
        url: "https://capitol.texas.gov/",
        publishedAt: "2026-04-08T12:00:00Z",
        sourceType: "bill_text",
      },
    ],
    impactSummary: {
      summary: "Texas operators need updated retention schedules and stronger audit trails for hybrid e-close packages.",
      impactLevel: "medium",
      affectedStakeholders: ["Texas title agents", "Operations leaders", "Records teams"],
      citations: ["Texas Legislature bill text"],
      freshnessLabel: "Updated 6 days ago",
      draft: true,
    },
    guidanceDraft: {
      summary: "Draft revised retention SOPs and digital closing evidence requirements ahead of effective date.",
      recommendedActions: [
        "Update Texas closing SOPs",
        "Review document retention controls for hybrid closings",
      ],
      citations: ["Texas Legislature bill text"],
      draft: true,
    },
    auditTrail: [
      {
        id: "audit-tx-sb1440-1",
        at: "2026-04-08T13:20:00Z",
        actor: "system:seed",
        action: "guidance.generated",
        detail: "Generated initial draft compliance guidance for passed Texas bill.",
      },
    ],
  },
  {
    id: "fl-hb-771",
    slug: "fl-hb-771-title-anti-fraud-controls",
    title: "Title Anti-Fraud Control Modernization Act",
    jurisdiction: "FL",
    billNumber: "HB 771",
    status: "in_committee",
    lastUpdated: "2026-04-11T16:45:00Z",
    titleRelevance: "Would require enhanced fraud-control attestations for title transfers and remote notarization.",
    summary: "Adds fraud-control certification and remote notarization review requirements for title transactions.",
    sourceDocuments: [
      {
        id: "src-fl-hb771",
        label: "Florida House bill summary",
        url: "https://www.flsenate.gov/",
        publishedAt: "2026-04-11T16:00:00Z",
        sourceType: "summary",
      },
    ],
    impactSummary: {
      summary: "Florida title shops may need new anti-fraud attestations and notary-control checklists in remote closing workflows.",
      impactLevel: "high",
      affectedStakeholders: ["Florida title agents", "Fraud teams", "Remote closing staff"],
      citations: ["Florida House bill summary"],
      freshnessLabel: "Updated 3 days ago",
      draft: true,
    },
    auditTrail: [
      {
        id: "audit-fl-hb771-1",
        at: "2026-04-11T16:47:00Z",
        actor: "system:seed",
        action: "bill.seeded",
        detail: "Seeded FL bill with committee-stage anti-fraud focus.",
      },
    ],
  },
  {
    id: "ny-s-5802",
    slug: "ny-s-5802-title-closing-fee-standardization",
    title: "Title Closing Fee Standardization Act",
    jurisdiction: "NY",
    billNumber: "S.5802",
    status: "introduced",
    lastUpdated: "2026-04-09T11:00:00Z",
    titleRelevance: "Could standardize closing-fee disclosures and endorsement fee language across New York filings.",
    summary: "Introduces uniform disclosure language for closing-related title fees and endorsement schedules.",
    sourceDocuments: [
      {
        id: "src-ny-s5802",
        label: "New York Senate bill summary",
        url: "https://www.nysenate.gov/",
        publishedAt: "2026-04-09T10:15:00Z",
        sourceType: "summary",
      },
    ],
    impactSummary: {
      summary: "Early-stage bill, but title carriers should watch for ripple effects across disclosure templates and filed schedules.",
      impactLevel: "medium",
      affectedStakeholders: ["New York underwriters", "Regulatory counsel"],
      citations: ["New York Senate bill summary"],
      freshnessLabel: "Updated 5 days ago",
      draft: true,
    },
    auditTrail: [
      {
        id: "audit-ny-s5802-1",
        at: "2026-04-09T11:05:00Z",
        actor: "system:seed",
        action: "bill.seeded",
        detail: "Seeded NY bill with intro-stage monitoring status.",
      },
    ],
  },
];
